version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - sam build
      - sam package --output-template-file scrum_pocker_api-packaged.yaml --s3-bucket TestBucket
artifacts:
  files:
    - scrum_pocker_api-packaged.yaml